### ISSUE TITLE
Init Lerna Monorepo - Merge repos

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/grida#56]
# (Draft) Merge Services into a single code base repository
Merge micro-splitted services (repositories) into this single repository.

**For..**
- Ease of management, contribution
- Ease of managing single oriented documentations
- To reduce redundant codes between UI required applications

### Repos to be merged into this repository
- Design To Code Engine - https://github.com/gridaco/designto-code
- Part of https://github.com/gridaco/grida.co (docs) or All of https://github.com/gridaco/grida.co
- Nothing Graphics Engine - https://github.com/gridaco/nothing
- Boring Text Engine - https://github.com/gridaco/boring
- Design server project - https://github.com/gridaco/design-server
- Design git project - https://github.com/gridaco/design-git

**Indeterminate**
- BASE - https://github.com/gridaco/base
- CoLI - https://github.com/gridaco/CoLI

### Projects (Repositories) that will be affected
- https://github.com/gridaco/assistant

### Pre-requirements
1. Setup this repo's submodules to the latest version
2. Making things work all together
3. 

### Todo
- [ ] Custom build script to silence vercel deployment for micro websites
- [ ] Additional Contributing.md to guide developers through working in a single-repository environment.
- [ ] Sub projects license management
- [ ] TBD..

### References
- Lerna.js
- Merging git repositories (preserve commit logs)

**Comment by softmarshmallow** [comment]
https://github.com/gridaco/grida/pull/62
